---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: macosx-10.10
    driver:
      provider: vmware_fusion
      box: macosx-10.10
      box_url: http://YOUR_SERVER_HERE/macosx-10.10.vmware.box

suites:
  - name: default
    run_list:
      - recipe[java-mac::default]
